version: '3.4'
services:
  ea_api:
    image: ea_api
    container_name: eaapi
    build:
      context: .
      dockerfile: ProductAPI/Dockerfile
    restart: on-failure      
    ports:
      - 5000:8001
    depends_on:
      - db
    networks:
      - ea_network

  ea_webapp:
    image: ea_webapp
    container_name: eawebapp
    build:
      context: .
      dockerfile: EAWebApp/Dockerfile
    restart: on-failure      
    ports:
      - 5001:8000
    depends_on: 
      - ea_api
    networks: 
      - ea_network

  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: "Password%1#29"
      ACCEPT_EULA: "Y"
    container_name: sqlserver
    hostname: sqlserver
    ports:
    - "1433:1433"
    networks:
      - ea_network

  ea_test:
    image: ea_test
    container_name: eatest
    build:
      context: .
      dockerfile: EATestBDD/Dockerfile
    restart: on-failure
    depends_on:
      - ea_api
      - selenium-hub
    networks:
      - ea_network

  node-docker:
    image: selenium/node-docker:4.1.1-20211217
    volumes:
      - ./assets:/opt/selenium/assets
      - ./GridConfig/config.toml:/opt/bin/config.toml
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    networks:
      - ea_network

  selenium-hub:
    image: selenium/hub:4.1.1-20211217
    container_name: selenium-hub
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"
    networks:
      - ea_network

networks: 
   ea_network: